### PR TITLE
I created my app using npx create-react-app

### PR DESCRIPTION
**Pull request by Arsalan74**

### CODE REVIEW

**Comment by sassanh** [comment]
Good job Arasalan! For future please just create pull requests and don't merge them until they are reviewed.

**Comment by Arsalan74** [comment]
Sure, thank you
Waiting for my next assignment 

Arsalan

**Comment by Arsalan74** [comment]
Dear Sassan,

Sorry for the delay I couldn’t done the assignment last night due to some unrelated problems.But I managed to review some things about Rect and I finished feature one in half an hour , today after 3 PM I will do the rest and send it to you if it’s ok.

Thank you
Arsalan


>

**Comment by Arsalan74** [comment]
Hello,

Feature 1 took me half an hour and feature 2 took me 3 hours
I reviewed some parts of a course from Udemy and it lasted 1:30 hours.
To sum up, I spend 7 hours for these tasks and reviews and other things like search engine hijackers! 

Thank you
Arsalan

**Pull request merged**
