### PR TITLE
Feature2

### PR DESCRIPTION
**Pull request by Arsalan74**
Refactoring the code using hooks

### CODE REVIEW

**Comment by sassanh** [comment]
Good job @Arsalan74! It looks very good, now I want you to keep it the way it is, and create another pull request branching from this branch (https://github.com/Arsalan74/To-Do-List/tree/feature2) and having the same destination, in this pull request I want you to bring eslint to the project and then lint your project with it so that it looks better and it is easier to read.

**Comment by sassanh** [comment]
Also please resolve the conflicts in this pull request, you should read about resolving conflicts using `git rebase` or `git merge`

**Comment by Arsalan74** [comment]
Ok I will do it by tomorrow 
Is it ok to fix the eslint comments automaticly or should I do it myself?

**Comment by sassanh** [comment]
@Arsalan74 It's OK to fix them automatically, but then you should review it in case it has done something weird that needs to be fixed manually.

**Comment by Arsalan74** [comment]
I installed eslint and used it.
I will read about git merge and rebase and I’ll explain it to you

**Comment by Arsalan74** [comment]
I merged the branches

**Comment by sassanh** [comment]
Instead of merging master into your branch so that it is updated with latest changes, you merged your branch into master directly, making the whole review process pointless.
This PR was incomplete and needed more work (specifically adding eslint) so please revert it and make a new PR.

**Comment by Arsalan74** [comment]
I think everything is ok now.

>

**Pull request merged**
